### ISSUE TITLE
Create Sub-Folders under Java Section

### ISSUE THREAD

**Issue by aayush89890** [Bauddhik-Geeks/Coding#3]
### Under Java main Folder We need to create Sub-Folders.

- [ ] Based on Different Platforms (eg: LeetCode, CodeChef, CodeForces, InterviewBit etc.)
- [ ]  Based on Different DSA Topics (eg: Arrays, String, Trees, Binary Trees, Graph, Stack, Queue etc.)

**Comment by aayush89890** [comment]
**I want to add labels to this issue and the future issues can I get access for that?**
@kamleshjoshi8102 @Nitesh-thapliyal

**Comment by Nitesh-thapliyal** [comment]
You can create folders for reference you can check the repo of C++

**Comment by aayush89890** [comment]
Yeah I know I can create but I want folks who are new to GitHub take up this issue. It will boost their confidence and grow our community.

**Comment by Nitesh-thapliyal** [comment]
> Yeah I know I can create but I want folks who are new to GitHub take up this issue. It will boost their confidence and grow our community.
> I am new to GitHub that is why I know how hard it is to make our first contribution.

💯

**Comment by aayush89890** [comment]
Thanks @Nitesh-thapliyal .
